### ISSUE TITLE
New UI menu control underneath Close and Full Screen buttons

### ISSUE THREAD

**Issue by kmandeville** [kbhomes/radiant-player-mac#320] opened 2015-05-14 18:17 UTC
The design of the app hides the left menu and the control to open and close it is directly underneath the OS X Close, Minimize, Full Screen buttons. Makes it tricky to use without closing the app. Also, the search box is where the window bar used to be to move the app around. Not really intuitive. Otherwise, I love the app!
![screen shot 2015-05-14 at 2 11 55 pm](https://cloud.githubusercontent.com/assets/1746424/7638579/e4b341ac-fa43-11e4-93db-84943dd6311d.png)

**Comment by tonybaroneee** [comment] 2015-05-14 19:29
Duplicate of https://github.com/kbhomes/radiant-player-mac/issues/318

**Comment by psyclone241** [comment] 2015-05-14 19:40
Your app is very nice, hopefully you are working on updating it. Thanks Google!!!

**Closed** 2015-06-05 07:07 UTC
