### ISSUE TITLE
Constantly freezes on Yosemite (10.10)

### ISSUE THREAD

**Issue by DataGreed** [kbhomes/radiant-player-mac#262] opened 2014-11-13 16:55 UTC
Player constantly freezes after playing 1-2 songs. The music itself continues playing and tracks keep changing forward, though media keys stop working, the player window becomes unresponsive (pinwheel cursor) and there's a pinwheel cursor above the tray icon.

I'm using mac pro 4,1 if it's any help and Radiant 1.3.1

**Comment by andrewjkerr** [comment] 2015-01-18 20:30
I've noticed the same thing, but only when I'm on the queue screen. If I'm not on the queue screen I won't notice any hangs at all.

However, I've noticed that the hangs will either be freezing or freezing AND a very unpleasant noise (I can't really describe it.) The noise seems to only happen when playing from a radio station.

I've got an Early 2011 15" MBP on 10.10.1 - 8GB RAM, 256GB SSD & 750GB HDD.

**Comment by hutchy2570** [comment] 2015-01-21 13:11
I've also noticed it only happens when the Queue screen is open, and normally when I'm using radio.  I managed to sample the app during a hang today. Don't know if it's of any use?

https://gist.github.com/hutchy2570/76f57ac54290e67b46b7

**Comment by hutchy2570** [comment] 2015-01-26 10:21
Just an update to this.  I've started seeing freezes when not on the queue page, and when not using Radio, so it doesn't seem to be just limited to those scenarios.  The hangs seem shorter when not on the queue page though.

**Comment by dodgepong** [comment] 2015-01-26 15:50
Been using the program for several months now, and ever since disabling notifications, it has run flawlessly.

**Comment by hutchy2570** [comment] 2015-01-29 11:24
@dodgepong is right. I disabled notifications 3 days ago after seeing his comment and the problem has completely disappeared.

**Comment by matthewlloyd** [comment] 2015-01-30 04:50
Disabling notifications worked for me too. I'm not really a Cocoa developer but based on symptoms, my guess is that the HTTP request to get the album thumbnail for the notification is blocking the main UI thread somehow.

**Comment by matthewlloyd** [comment] 2015-01-30 04:57
Took a quick look, my hunch was correct, as confirmed by a read of the code and the gist stack thread posted at the top of this conversation. The problem is this line:

https://github.com/kbhomes/radiant-player-mac/blob/master/radiant-player-mac/Notifications/NotificationCenter.m#L78

If the HTTP request for the image takes a long time, it hangs the entire application until it either succeeds or times out. The fix would be to have the notification (or just the image load part if possible) run in a separate thread.

**Comment by hutchy2570** [comment] 2015-01-30 09:19
@matthewlloyd I turned notifications back on and started getting hangs again, turned off the album art in notifications and the hangs stopped occurring, so looks like that is the culprit.  Hopefully it's an easy fix as album art in the notification is quite nice.

**Comment by DataGreed** [comment] 2015-01-30 09:48
Can it be also a culprit of CPU hoging?

**Comment by kbhomes** [comment] 2015-02-16 02:30
Could you guys take a look at #280 and run the pre-release version, see if you're having any problems still?

**Comment by hu5h55** [comment] 2015-02-16 08:53
Thanks man, will try it out through the day.
Regards
Niclas

**Comment by ShutterMunster** [comment] 2015-02-16 09:05
Turning on notifications and giving the new one a shot now. Working well so far. Will report otherwise. 

Thanks kid!

---
Roman France
Motion // Stills
RomanM Photography


On February 15, 2015 at 9:30:07 PM, Sajid Anwar (notifications@github.com) wrote:

Could you guys take a look at #280 and run the pre-release version, see if you're having any problems still?

**Comment by hu5h55** [comment] 2015-02-18 09:19
Seems to be stable so far! Will report if I find anything.
Thanks! Keep up the good work!

**Comment by kbhomes** [comment] 2015-02-19 18:21
Thanks for the heads up @matthewlloyd, I just pushed a fix for that problem.

**Closed** 2015-02-19 18:21 UTC
