### ISSUE TITLE
UI Broken And Music Not Playing

### ISSUE THREAD

**Issue by JustinTBrown** [kbhomes/radiant-player-mac#351] opened 2015-08-19 17:40 UTC
I have verion 1.4.0 installed and am running OS X 10.10.4.

I've been using 1.4.0 without issue for several weeks now. About 2 days ago part of the bottom UI disappeared. I've included a screenshot below.

![screen shot 2015-08-19 at 11 34 26 am](https://cloud.githubusercontent.com/assets/1620519/9363929/acdd7d3c-4666-11e5-9bc2-7f77396234fc.png)

There aren't any error message that I can see. Just that odd white block.

**Comment by Yurtledaturtle** [comment] 2015-08-19 21:01
I have had the same happen to me too :(

**Comment by ollien** [comment] 2015-08-19 21:38
Seems to be the same issue as when the UI updated :/

**Comment by JustinTBrown** [comment] 2015-08-19 23:35
@Yurtledaturtle yes that is true for me also, I should have mentioned that. I cannot play anything.

**Comment by joshuafcole** [comment] 2015-08-20 00:22
Also effected. Let me know if there's any diagnostic information I can provide.

**Comment by ChromoX** [comment] 2015-08-20 03:43
Same here.

**Comment by afunix** [comment] 2015-08-20 07:09
Same here

**Comment by jackbentley** [comment] 2015-08-20 10:11
Same here

**Comment by davidhatten** [comment] 2015-08-20 12:41
I'm not sure when I updated vs when it broke, but I am also seeing the white box and I am also unable to play music

**Comment by colincsl** [comment] 2015-08-20 14:17
+1

**Comment by boojew** [comment] 2015-08-20 15:10
Same here. Worth noting, it works in Safari and there doesnt appear to be any flash updates.

**Comment by rnavarropiris** [comment] 2015-08-20 16:01
same over here, running 10.10.5

**Comment by shawn-mitch** [comment] 2015-08-20 16:41
+1 For me it just started this morning. It was working about 18 hours ago.

**Comment by rickarubio** [comment] 2015-08-20 16:43
Also on 10.10.4 and 1.4, seeing same issue as OP.

**Comment by tonatiuh** [comment] 2015-08-20 16:48
Same here.

**Comment by jakechs** [comment] 2015-08-20 17:30
Started last night for me, no clear cause. I was using it happily all day and then brought my computer home and nothing worked. 

I botched a 10.10.5 update and also installed the "Digital Camera RAW Compatibility Update 6.06", but I don't think either of these happened directly before the problem, just around the same time.

**Comment by foglerek** [comment] 2015-08-20 17:30
Sadly, I think this is Google trying to counteract the player. Just broke yesterday for me.

**Comment by Yurtledaturtle** [comment] 2015-08-20 17:37
@foglerek I have a suspicion that you are correct, I was wondering how long we were gonna have to enjoy the player until Google eventually took action. Especially because I believe the issue occurred without the player receiving any update :(

**Comment by jadengore** [comment] 2015-08-20 17:58
:cry:

**Comment by thedapmonster** [comment] 2015-08-20 20:18
i hope foglerek and yurtledaturtle are not right. this is the best player ive ever used.

**Comment by shawn-mitch** [comment] 2015-08-20 20:52
@thedapmonster Same here. This player is leaps and bounds above using Google Music in a browser. There are other standalone players but I haven't looked at any of them since installing Radiant Player.

**Comment by j-bro** [comment] 2015-08-21 03:50
Same problem here

**Comment by mlmilliman** [comment] 2015-08-21 03:54
I guess I'll jump on the bandwagon and +1.

**Comment by belen-albeza** [comment] 2015-08-21 07:51
+1 here. Also maybe it would be good to rename the bug to `UI broken and audio not playing`, it's more descriptive.

**Comment by japhex** [comment] 2015-08-21 09:23
+1 here also, this started yesterday for me, I don't want to use anything else, I'm an avid last.fm user still and this app is perfect!

**Comment by FezVrasta** [comment] 2015-08-21 11:00
Same here :/

**Comment by Seblirium** [comment] 2015-08-21 13:35
+1

As posted earlier, it seems to be the same/similar issue to the one a few months back.

**Comment by jboolean** [comment] 2015-08-21 13:49
+1

**Comment by NormandLemay** [comment] 2015-08-21 13:55
+1

**Comment by tspaulding0222** [comment] 2015-08-21 14:14
Ran into this bug also. Interesting how it happened at complete random. Never saw an update log from google

**Comment by mmoloksher** [comment] 2015-08-21 15:23
+1

**Comment by interactivematt** [comment] 2015-08-21 15:41
+1

**Comment by Squintz82** [comment] 2015-08-21 15:56
+1

**Comment by rlschroeder** [comment] 2015-08-21 15:58
+1

**Comment by brandonskane** [comment] 2015-08-21 17:07
+1

**Comment by patrickhpan** [comment] 2015-08-22 00:37
+1. Until a fix is found, I'm using scroblr (link under) for last.fm. https://chrome.google.com/webstore/detail/mflbcmpjneookibbaeopkfcnegknkgog

**Comment by bcow** [comment] 2015-08-22 02:41
+1

**Comment by churchid** [comment] 2015-08-22 03:30
+1

**Comment by benburton** [comment] 2015-08-22 13:40
+1

**Comment by mlmilliman** [comment] 2015-08-22 19:02
It is interesting that the developer hasn't checked in on this topic. To my knowledge Radiant Player mimics a webkit browser so Play Music doesn't know the difference from Safari or whatever browser type the application returns. On the other hand, it does play properly in Safari and Chrome so maybe his browser type string is being caught. I'd troubleshoot it but I'm dealing with another Android issue at the moment.

**Comment by lleolin** [comment] 2015-08-22 21:08
Not certain but I suspected that it was related to Flash. The UI looks similar to how it does when I don't have Flash enabled in my browser. The same types of controls are blanked out and unusable.
<img width="1440" alt="screen shot 2015-08-22 at 5 04 58 pm" src="https://cloud.githubusercontent.com/assets/11459455/9425868/31cc91b4-48f0-11e5-9fd4-054731d6b248.png">
<img width="1433" alt="screen shot 2015-08-22 at 5 05 45 pm" src="https://cloud.githubusercontent.com/assets/11459455/9425869/3487484a-48f0-11e5-98c2-104007c4ba0b.png">

**Comment by jkchambers** [comment] 2015-08-22 21:37
I've noticed that minimizing the player and bringing it back up solves the white box. The music will queue but will never load. Sometimes it skips through saying that the song could't be played (similar to if there was no internet connection). Play Music works perfectly on safari and even notes that another device is trying to play music. No idea if that helps identify the problem.

Fresh download of flash and Radiant.

**Comment by shawn-mitch** [comment] 2015-08-22 22:22
@kbhomes If you're going to ignore this issue, can you at least push the latest branch? The current master is 1.3.3.2-beta. I was going to poke around for issues but I'm not going to waste my time with something that's a couple weeks (months?) older than current.

**Comment by lleolin** [comment] 2015-08-23 00:31
@jkchambers That seems to be the case. Guess it has nothing to do with Flash.

**Comment by jacobwgillespie** [comment] 2015-08-23 00:36
Found it guys - Radiant uses a custom patched version of the `webcomponents.js` file that Google serves (see 7cbdb20 for more background), and Google renamed it from `webcomponents.js` to `webcomponents.min.js`, which broke the substitution.  Submitted PR #352 as a fix - it's working in my local builds.

**Comment by shawn-mitch** [comment] 2015-08-23 01:27
@jacobwgillespie Your fix worked for me. Good work!

**Comment by thedapmonster** [comment] 2015-08-23 01:42
Woo-hoo Jacob G!

**Comment by jadengore** [comment] 2015-08-23 02:17
@jacobwgillespie, while we wait for your PR can you post a binary of your working version so people can get their fix? I tried building locally, but the problem is still there for me...

**Comment by jacobwgillespie** [comment] 2015-08-23 04:10
Here's the latest build: https://dl.dropboxusercontent.com/u/6278910/Radiant%20Player.zip.  Do be aware though that the version number on GitHub is 1.3.3.2-beta, which is behind the latest published 1.4.0.  I changed the version number of the build here to 1.4.0 so that it wouldn't prompt to upgrade, but it's likely not exactly the same as the 1.4.0 build.  You should definitely replace this build with the correct one once @kbhomes pushes a fix.  

I can relate to wanting this fixed ASAP though, as it's been annoying these past few days pressing media buttons on my keyboard and having nothing happen.  :stuck_out_tongue:

**Comment by p-becker** [comment] 2015-08-23 12:14
@jacobwgillespie Thanks, working perfectly!

**Comment by tonatiuh** [comment] 2015-08-23 14:05
Great job @jacobwgillespie! this is working for me as well. I hope your PR is merged soon.

**Comment by rickarubio** [comment] 2015-08-23 21:05
@jacobwgillespie nice catch, thanks! :tada:

**Comment by japhex** [comment] 2015-08-24 08:18
@jacobwgillespie - absolute legend! Thanks man, works fine now. That's such a silly error!

**Comment by Seblirium** [comment] 2015-08-24 08:31
@jacobwgillespie <https://github.com/jacobwgillespie> - Thank you; working
as expected now.

**Comment by emvavra** [comment] 2015-08-24 09:16
@jacobwgillespie many thanks for the build! :+1:

**Comment by Yurtledaturtle** [comment] 2015-08-24 14:06
@jacobwgillespie Thanks a bunch!

**Comment by benmeroff** [comment] 2015-08-24 14:24
@jacobwgillespie You rock, great fix!

**Comment by benburton** [comment] 2015-08-24 14:25
Thanks @jacobwgillespie :+1:

**Comment by mlmilliman** [comment] 2015-08-24 14:55
Thanks so much @jacobwgillespie! Great catch and quick fix for @kbhomes. I made an applet from Chrome as a temporary workaround, but it opens another instance of Chrome, consumes too much memory, and doesn't integrate with OS X as well especially with the media keys and notifications.

**Comment by Teumer** [comment] 2015-08-24 16:57
@jacobwgillespie much appreciated

**Comment by Schrobie** [comment] 2015-08-24 18:22
@jacobwgillespie nice work!

**Comment by mkotb** [comment] 2015-08-24 18:38
@jacobwgillespie +1 tyvm, works perfectly!

**Comment by DotTheI** [comment] 2015-08-24 18:45
@jacobwgillespie Thank you!

**Comment by dustincoates** [comment] 2015-08-25 02:53
@jacobwgillespie This is fantastic, thanks!

**Comment by chroust** [comment] 2015-08-25 07:00
@jacobwgillespie Thank you, working perfectly!

**Comment by JustinTBrown** [comment] 2015-08-25 15:02
@jacobwgillespie Many thanks!!!

**Comment by kdschaffe** [comment] 2015-08-26 01:54
I'm a little late to this party but the dropbox link is giving me a 500 error. Any help would be great. Thanks for the quick fix!

**Comment by jadengore** [comment] 2015-08-26 04:27
@kdschaffe I just tried it and it worked... I'll upload a mirror for you

**Comment by jadengore** [comment] 2015-08-26 04:35
@kdschaffe and anyone else, here's a mirror link: https://www.mediafire.com/?3tfh0av7u92ytly

**Comment by kdschaffe** [comment] 2015-08-26 04:47
Tried again and it's working.. The mirror is good too tho so thanks @jadengore. The fix is also working. Love the community!

**Comment by Delallen** [comment] 2015-08-26 15:26
Thanks @jadengore mirror download working. You saved my productivity.

**Comment by josejulio** [comment] 2015-08-26 21:50
Thanks!

**Comment by kitze** [comment] 2015-08-27 11:58
@jadengore  @jacobwgillespie thanks guys!

**Comment by jacobwgillespie** [comment] 2015-08-27 19:32
No problem, happy to help!  Added https://mega.nz/#!L4lxSJZa!LyvkNSmoGnUtGisxNdEBtQq2Hg17C1QUYgFryDQkk2Y as a mirror as well in case Dropbox keeps acting up.

**Comment by chrismou** [comment] 2015-08-28 12:09
(Y) Cheers dude, much appreciated. Had no idea how much I'd got used to pausing/skipping songs using the keyboard controls!

**Comment by mgmcgithub** [comment] 2015-08-28 16:17
+1, the new build works perfectly for me.  Thank you.

**Comment by jadengore** [comment] 2015-08-28 17:07
@chrismou You can use your keyboard controls  in Chrome as well using [Prime Player](https://chrome.google.com/webstore/detail/prime-player-for-google-p/npngaakpdgeaajbnidkkginekmnaejbi?hl=en), it's not exclusive to Radiant. In the future we might have to switch to this solution anyways if @kbhomes does not continue support for this app.

**Comment by chrismou** [comment] 2015-08-28 17:10
@jadengore I'm sure he's just a bit busy with real life at the moment.

And if not, the joy of open source is any of us can continue its development ;-)

**Comment by mfkp** [comment] 2015-08-28 17:12
@chrismou @jadengore I've been using [Stream Keys](http://www.streamkeys.com/), same purpose, been working well.

**Comment by JustJenFelice** [comment] 2015-08-28 19:45
@jadengore @jacobwgillespie  thanks so much for this - been suffering for days.

**Comment by afunix** [comment] 2015-08-30 10:49
Are there any plans to release an official build? @kbhomes ?

**Comment by geddski** [comment] 2015-09-02 20:14
had same issue. Using the temp build shared above. Thx

**Comment by yanismydj** [comment] 2015-09-09 00:30
shout out to @jacobwgillespie for the fix! thanks!

**Comment by taolmsted** [comment] 2015-09-13 12:14
I've also been experiencing the issue the OP described.  Thanks for the temporary fix!

**Closed** 2015-09-14 00:58 UTC

**Comment by nicolaspy** [comment] 2015-09-22 16:49
@jacobwgillespie Thanks much!

**Comment by jacobwgillespie** [comment] 2015-10-04 15:58
Pushed an updated build with El Capitan support as well here: https://github.com/jacobwgillespie/radiant-player-mac/releases/tag/v1.4.0.  As before, switch to 1.4.1 as soon as @kbhomes pushes a new build.  Cheers!
